version: "3.8"
services:
  nginx:
    depends_on:
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: nginx
    ports:
      - "80:80"
#    deploy:
#        resources:
#          limits:
#            cpus: "2.0"
#            memory: "16g"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./